# Generated by Django 4.2.7 on 2026-03-05 06:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import random
import string


def _generate_unique_code(User):
    alphabet = string.ascii_uppercase + string.digits
    while True:
        length = random.randint(6, 10)
        code = ''.join(random.choice(alphabet) for _ in range(length))
        if not User.objects.filter(invite_code=code).exists():
            return code


def populate_invite_codes(apps, schema_editor):
    User = apps.get_model('users', 'User')
    users = User.objects.filter(models.Q(invite_code__isnull=True) | models.Q(invite_code=''))
    for user in users.iterator():
        user.invite_code = _generate_unique_code(User)
        user.save(update_fields=['invite_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUALIFIED', 'Qualified'), ('REWARDED', 'Rewarded'), ('INVALID', 'Invalid')], default='PENDING', max_length=20)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qualified_deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invalid_reason', models.CharField(blank=True, max_length=255)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to='users.user'),
        ),
        migrations.RunPython(populate_invite_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='ReferralEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REFERRAL_REGISTERED', 'Referral Registered'), ('REFERRAL_QUALIFIED', 'Referral Qualified'), ('REFERRAL_REWARDED', 'Referral Rewarded'), ('REFERRAL_INVALIDATED', 'Referral Invalidated')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.referral')),
            ],
            options={
                'db_table': 'referral_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='referral',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_referrals', to='users.user'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['inviter', 'status'], name='referrals_inviter_7e3ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status', 'created_at'], name='referrals_status_918a2d_idx'),
        ),
    ]
