# Generated by Django 4.2.7 on 2026-04-16 19:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_referral_user_invite_code_user_referral_count_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo')], default='text', max_length=20)),
                ('message', models.TextField()),
                ('photo_file_id', models.CharField(blank=True, max_length=255)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_logs', to='users.user')),
            ],
            options={
                'db_table': 'announcement_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
