"""
Django settings for bingo_project project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import importlib
from dotenv import load_dotenv


def env_bool(name: str, default: bool = False) -> bool:
    return os.getenv(name, 'True' if default else 'False').lower() in {'1', 'true', 'yes', 'on'}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
# Base .env is always loaded first. In development, .env.development can override it.
load_dotenv(BASE_DIR / '.env')
django_env = os.getenv('DJANGO_ENV', '').strip().lower()
if django_env in {'dev', 'development', 'local'}:
    load_dotenv(BASE_DIR / '.env.development', override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', False)

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'dev-insecure-change-me'
    else:
        import secrets
        SECRET_KEY = secrets.token_urlsafe(50)  # Auto-generate if not set

allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '')
if allowed_hosts_env.strip():
    ALLOWED_HOSTS = []
    for host in allowed_hosts_env.split(','):
        item = host.strip().replace('https://', '').replace('http://', '').rstrip('/')
        if item:
            ALLOWED_HOSTS.append(item)
elif DEBUG:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
else:
    ALLOWED_HOSTS = []

render_host = os.getenv('RENDER_EXTERNAL_HOSTNAME', '').strip()
if render_host and render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_host)

if not ALLOWED_HOSTS:
    if DEBUG:
        ALLOWED_HOSTS = ['*']
    else:
        ALLOWED_HOSTS = ['*']  # Render sets RENDER_EXTERNAL_HOSTNAME automatically


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    # Custom apps
    "users",
    "wallet",
    "game.apps.GameConfig",
    "notifications",
    "corsheaders",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "bingo_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "bingo_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

database_url = os.getenv("DATABASE_URL", "").strip()
if database_url:
    dj_database_url = importlib.import_module("dj_database_url")
    DATABASES = {
        "default": dj_database_url.parse(database_url, conn_max_age=600)
    }
else:
    DB_NAME = os.getenv("DB_NAME")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": DB_NAME,
            "USER": os.getenv("DB_USER", "postgres"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": int(os.getenv("DB_PORT", "5432")),
        }
    }

# SQLite config (alternative for development)
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# Game Configuration
WELCOME_BONUS = int(os.getenv('WELCOME_BONUS', 10))
# Legacy single-price fallback (used when a specific game stake is not available)
CARD_PRICE = int(os.getenv('CARD_PRICE', 10))
GAME_STAKE_TIERS = [
    int(value.strip())
    for value in os.getenv('GAME_STAKE_TIERS', '10,20,50,100').split(',')
    if value.strip()
]
if not GAME_STAKE_TIERS:
    GAME_STAKE_TIERS = [10, 20, 50, 100]
CARD_COUNT = int(os.getenv('CARD_COUNT', 400))
MIN_DEPOSIT = int(os.getenv('MIN_DEPOSIT', 10))
REFERRAL_REWARD = int(os.getenv('REFERRAL_REWARD', 10))
MIN_DEPOSIT_FOR_REWARD = int(os.getenv('MIN_DEPOSIT_FOR_REWARD', 20))
MAX_REWARDED_REFERRALS_PER_DAY = int(os.getenv('MAX_REWARDED_REFERRALS_PER_DAY', 20))
MAX_TOTAL_REFERRAL_REWARDS_PER_USER = int(os.getenv('MAX_TOTAL_REFERRAL_REWARDS_PER_USER', 0))
MIN_WITHDRAWAL = int(os.getenv('MIN_WITHDRAWAL', 100))
WAITING_TIME = int(os.getenv('WAITING_TIME', 25))
NUMBER_CALL_INTERVAL = int(os.getenv('NUMBER_CALL_INTERVAL', 5))
BINGO_NUMBER_MAX = int(os.getenv('BINGO_NUMBER_MAX', 75))
GAME_MIN_PLAYERS = int(os.getenv('GAME_MIN_PLAYERS', 2))

# Bot Configuration
BOT_TOKEN = os.getenv('BOT_TOKEN', '')
BOT_USERNAME = os.getenv('BOT_USERNAME', 'bingo_bot')
ADMIN_IDS = [int(id.strip()) for id in os.getenv('ADMIN_IDS', '').split(',') if id.strip()]
ADMIN_LOGIN_TOKEN = os.getenv('ADMIN_LOGIN_TOKEN', '').strip()

# React UI Configuration
USE_REACT_UI = os.getenv('USE_REACT_UI', 'True') == 'True'
REACT_APP_URL = os.getenv('REACT_APP_URL', 'https://bingo-game-1-5kj6.onrender.com')

web_allowed_origins_env = os.getenv('WEB_ALLOWED_ORIGINS', '')
WEB_ALLOWED_ORIGINS = [
    REACT_APP_URL.rstrip('/'),
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
if web_allowed_origins_env.strip():
    WEB_ALLOWED_ORIGINS.extend(
        origin.strip().rstrip('/') for origin in web_allowed_origins_env.split(',') if origin.strip()
    )
WEB_ALLOWED_ORIGINS = list(dict.fromkeys(WEB_ALLOWED_ORIGINS))

csrf_trusted_origins_env = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if csrf_trusted_origins_env.strip():
    CSRF_TRUSTED_ORIGINS = [origin.strip().rstrip('/') for origin in csrf_trusted_origins_env.split(',') if origin.strip()]
else:
    CSRF_TRUSTED_ORIGINS = [origin for origin in WEB_ALLOWED_ORIGINS if origin.startswith('http://') or origin.startswith('https://')]

# Frontend is deployed on a separate Render domain, so API requests need CORS.
CORS_ALLOWED_ORIGINS = [origin for origin in WEB_ALLOWED_ORIGINS if origin.startswith('http://') or origin.startswith('https://')]
cors_allowed_origin_regexes_env = os.getenv('CORS_ALLOWED_ORIGIN_REGEXES', '').strip()
if cors_allowed_origin_regexes_env:
    CORS_ALLOWED_ORIGIN_REGEXES = [item.strip() for item in cors_allowed_origin_regexes_env.split(',') if item.strip()]
else:
    CORS_ALLOWED_ORIGIN_REGEXES = [r'^https://[a-z0-9-]+\.onrender\.com$']
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-user-token",
]

# Payment Configuration
TELEBIRR_NUMBER = os.getenv('TELEBIRR_NUMBER', '0912345678')


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_BACKEND = os.getenv(
    "STATICFILES_BACKEND",
    "whitenoise.storage.CompressedStaticFilesStorage",
)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": STATICFILES_BACKEND,
    },
}
# Fallback to app/static discovery (including Django admin assets) if collectstatic output is missing.
WHITENOISE_USE_FINDERS = env_bool("WHITENOISE_USE_FINDERS", True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Production security headers and cookie flags
if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', True)
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', True)
    SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', True)
    SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', True)
    CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', True)
    SECURE_BROWSER_XSS_FILTER = env_bool('SECURE_BROWSER_XSS_FILTER', True)
    SECURE_CONTENT_TYPE_NOSNIFF = env_bool('SECURE_CONTENT_TYPE_NOSNIFF', True)
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'same-origin'
