# Generated by Django 4.2.7 on 2026-03-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_add_winnings_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('game_entry', 'Game Entry'), ('game_win', 'Game Win'), ('bonus', 'Bonus'), ('referral_bonus', 'Referral Bonus'), ('admin_adjustment', 'Admin Adjustment')], max_length=20),
        ),
    ]
