# Generated by Django 4.2.11 on 2026-04-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0006_transaction_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="extracted_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deposit",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
