# Generated by Django 4.2.7 on 2026-02-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_bingocard_custom_grid"),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='system_revenue',
            field=models.DecimalField(max_digits=10, decimal_places=2, default=0),
        ),
    ]
