# Generated by Django 4.2.7 on 2026-03-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_stakelobbylock'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='systembalanceledger',
            new_name='system_bala_event_t_c9ddad_idx',
            old_name='system_bala_event_t_53be50_idx',
        ),
        migrations.RenameIndex(
            model_name='systembalanceledger',
            new_name='system_bala_created_317d74_idx',
            old_name='system_bala_created_58d679_idx',
        ),
    ]
