# Generated by Django 4.2.7 on 2026-03-21 06:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_referral_user_invite_code_user_referral_count_and_more'),
        ('game', '0009_rename_system_bala_event_t_53be50_idx_system_bala_event_t_c9ddad_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('event_type', models.CharField(choices=[('happy_hour', 'Happy Hour'), ('flash_promo', 'Flash Promo'), ('double_reward', 'Double Reward')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('bonus_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_announce', models.BooleanField(default=True)),
                ('announced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'live_events',
                'ordering': ['starts_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MissionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('mission_type', models.CharField(choices=[('play_games', 'Play Games'), ('win_games', 'Win Games'), ('redeem_promo', 'Redeem Promo'), ('invite_users', 'Invite Users')], max_length=30)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('target_value', models.IntegerField(default=1)),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reward_balance', models.CharField(choices=[('bonus', 'Bonus Balance'), ('main', 'Main Balance'), ('winnings', 'Winnings Balance')], default='bonus', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mission_templates',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('tier', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reward_balance', models.CharField(choices=[('bonus', 'Bonus Balance'), ('main', 'Main Balance'), ('winnings', 'Winnings Balance')], default='bonus', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('max_redemptions', models.IntegerField(default=0)),
                ('per_user_limit', models.IntegerField(default=1)),
                ('min_account_age_days', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'promo_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardSafetyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_reward_cap', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10)),
                ('min_seconds_between_rewards', models.IntegerField(default=20)),
                ('max_reward_redemptions_per_hour', models.IntegerField(default=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reward_safety_policy',
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('streak_protect_tokens', models.IntegerField(default=1)),
                ('last_protect_grant_week', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='users.user')),
            ],
            options={
                'db_table': 'user_streaks',
            },
        ),
        migrations.CreateModel(
            name='UserRewardWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_date', models.DateField()),
                ('reward_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('redemption_count', models.IntegerField(default=0)),
                ('last_reward_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_windows', to='users.user')),
            ],
            options={
                'db_table': 'user_reward_window',
            },
        ),
        migrations.CreateModel(
            name='UserMissionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('progress_value', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='game.missiontemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_progress', to='users.user')),
            ],
            options={
                'db_table': 'user_mission_progress',
                'ordering': ['-period_start', 'mission_id'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('top_1_reward', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('top_2_reward', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('top_3_reward', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('participation_reward', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seasons',
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='seasons_is_acti_11a1d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PromoCodeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='game.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to='users.user')),
            ],
            options={
                'db_table': 'promo_code_redemptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code'], name='promo_codes_code_5b1d05_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='promo_codes_is_acti_8fee7e_idx'),
        ),
        migrations.AddIndex(
            model_name='missiontemplate',
            index=models.Index(fields=['is_active', 'period'], name='mission_tem_is_acti_c6722a_idx'),
        ),
        migrations.AddIndex(
            model_name='missiontemplate',
            index=models.Index(fields=['mission_type'], name='mission_tem_mission_db873d_idx'),
        ),
        migrations.AddIndex(
            model_name='liveevent',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='live_events_is_acti_4b1252_idx'),
        ),
        migrations.AddIndex(
            model_name='liveevent',
            index=models.Index(fields=['event_type'], name='live_events_event_t_cda03f_idx'),
        ),
        migrations.AddIndex(
            model_name='userrewardwindow',
            index=models.Index(fields=['reward_date'], name='user_reward_reward__6bc789_idx'),
        ),
        migrations.AddIndex(
            model_name='userrewardwindow',
            index=models.Index(fields=['user', 'reward_date'], name='user_reward_user_id_fb520b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrewardwindow',
            unique_together={('user', 'reward_date')},
        ),
        migrations.AddIndex(
            model_name='usermissionprogress',
            index=models.Index(fields=['user', 'period_start'], name='user_missio_user_id_42c639_idx'),
        ),
        migrations.AddIndex(
            model_name='usermissionprogress',
            index=models.Index(fields=['period_end'], name='user_missio_period__dfc59e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermissionprogress',
            unique_together={('user', 'mission', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='promocoderedemption',
            index=models.Index(fields=['promo_code', 'created_at'], name='promo_code__promo_c_3d6309_idx'),
        ),
        migrations.AddIndex(
            model_name='promocoderedemption',
            index=models.Index(fields=['user', 'created_at'], name='promo_code__user_id_6e893b_idx'),
        ),
    ]
