# Generated by Django 4.2.7 on 2026-03-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_seed_engagement_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='is_visible_in_frontend',
            field=models.BooleanField(default=True),
        ),
    ]
