# Generated by Django 4.2.7 on 2026-03-23 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_promocode_is_visible_in_frontend'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEngineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_fake_users', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'game_engine_settings',
            },
        ),
    ]
