# Generated by Django 4.2.7 on 2026-03-23 00:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_gameenginesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardsafetypolicy',
            name='low_system_balance_warning_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10),
        ),
    ]
