# Generated by Django 4.2.7 on 2026-04-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_rewardsafetypolicy_low_system_balance_warning_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systembalanceledger',
            name='event_type',
            field=models.CharField(choices=[('game_commission', 'Game Commission'), ('game_no_winner', 'Game No Winner'), ('reward_payout', 'Reward Payout'), ('admin_adjustment', 'Admin Adjustment')], max_length=30),
        ),
    ]
