# Generated by Django 4.2.7 on 2026-04-16 18:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_referral_user_invite_code_user_referral_count_and_more'),
        ('game', '0015_alter_systembalanceledger_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRuleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_withdrawable_balance', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('referral_bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('derash_percentage', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('system_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('telebirr_receiving_phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Ethiopian phone number (e.g. 09XXXXXXXX or +2519XXXXXXXX).', regex='^(?:\\+?2519\\d{8}|09\\d{8})$')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_business_rule_settings', to='users.user')),
            ],
            options={
                'db_table': 'business_rule_settings',
            },
        ),
        migrations.CreateModel(
            name='PromoVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_verification', max_length=30)),
                ('review_reason', models.TextField(blank=True)),
                ('decision_time', models.DateTimeField(blank=True, null=True)),
                ('credited_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('admin_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_promo_verifications', to='users.user')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='game.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_verification_requests', to='users.user')),
            ],
            options={
                'db_table': 'promo_verification_requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessRuleSettingsAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='game.businessrulesettings')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_rule_audit_entries', to='users.user')),
            ],
            options={
                'db_table': 'business_rule_settings_audit',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddField(
            model_name='promocoderedemption',
            name='verification_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemption', to='game.promoverificationrequest'),
        ),
        migrations.AddIndex(
            model_name='promoverificationrequest',
            index=models.Index(fields=['status', 'submitted_at'], name='promo_verif_status_d1ded2_idx'),
        ),
        migrations.AddIndex(
            model_name='promoverificationrequest',
            index=models.Index(fields=['user', 'submitted_at'], name='promo_verif_user_id_bbe198_idx'),
        ),
        migrations.AddIndex(
            model_name='promoverificationrequest',
            index=models.Index(fields=['promo_code', 'submitted_at'], name='promo_verif_promo_c_76dafc_idx'),
        ),
    ]
