# Generated by Django 4.2.7 on 2026-04-17 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_businessrulesettings_promoverificationrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrulesettings',
            name='countdown_seconds',
            field=models.PositiveIntegerField(default=25, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)]),
        ),
    ]
