# Generated by Django 4.2.7 on 2026-04-19 03:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_businessrulesettings_countdown_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrulesettings',
            name='rejoin_start_delay_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Additional delay before game start when players return to a previously lonely lobby.', validators=[django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='businessrulesettings',
            name='telebirr_receiving_account_name',
            field=models.CharField(default='Bingo Bot', max_length=120),
        ),
    ]
