# Generated by Django 4.2.7 on 2026-04-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0019_businessrulesettings_winner_announcement_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessrulesettings",
            name="invitations_enabled",
            field=models.BooleanField(
                default=True, help_text="Enable or disable user invitations/referrals"
            ),
        ),
    ]
