# Generated by Django 4.2.7 on 2026-02-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('game_entry', 'Game Entry'), ('game_win', 'Game Win'), ('bonus', 'Bonus'), ('admin_adjustment', 'Admin Adjustment')], max_length=20),
        ),
    ]
