# Generated by Django 4.2.20 on 2026-02-09 15:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("no_game", "No Game"),
                            ("waiting", "Waiting"),
                            ("playing", "Playing"),
                            ("finished", "Finished"),
                        ],
                        default="no_game",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "prize_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("called_numbers", models.TextField(default="[]")),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_games",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "games",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BingoCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.IntegerField()),
                ("grid", models.TextField()),
                ("marked_positions", models.TextField(default="[]")),
                ("is_winner", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="game.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bingo_cards",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "bingo_cards",
                "unique_together": {("game", "card_number")},
            },
        ),
    ]
