# Generated by Django 4.2.7 on 2026-02-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_remove_bingocard_grid"),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='has_bots',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='real_players_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='real_prize_amount',
            field=models.DecimalField(max_digits=10, decimal_places=2, default=0),
        ),
    ]
