# Generated by Django 4.2.7 on 2026-02-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_add_bot_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="bingocard",
            name="custom_grid",
            field=models.TextField(blank=True, null=True),
        ),
    ]
