# Generated by Django 4.2.7 on 2026-03-02 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_add_system_revenue"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemBalance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("balance", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "system_balance",
            },
        ),
        migrations.CreateModel(
            name="SystemBalanceLedger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("game_commission", "Game Commission"),
                            ("game_no_winner", "Game No Winner"),
                            ("admin_adjustment", "Admin Adjustment"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("balance_before", models.DecimalField(decimal_places=2, max_digits=14)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=14)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("idempotency_key", models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_balance_entries",
                        to="game.game",
                    ),
                ),
            ],
            options={
                "db_table": "system_balance_ledger",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["event_type"], name="system_bala_event_t_53be50_idx"),
                    models.Index(fields=["created_at"], name="system_bala_created_58d679_idx"),
                ],
            },
        ),
    ]
