# Generated by Django 4.2.7 on 2026-04-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_referral_user_invite_code_user_referral_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_site_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
